field: b20240ab-6495-4623-b16d-6ac8c2e80970
fieldLayouts:
  294b0263-5e22-4eee-b376-a89fe82ee316:
    tabs:
      -
        elements:
          -
            fieldUid: 73d48d09-f11a-4dcd-9129-f1081e824770
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 83d4dc8a-1b63-4599-870b-4d1cc105caac
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e6e287b3-e9ab-43a5-a89a-11cdc02cef8b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 83cb90e8-c6dd-4b41-8123-a0cfa1011b05
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  73d48d09-f11a-4dcd-9129-f1081e824770:
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: ''
    name: Copy
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  83cb90e8-c6dd-4b41-8123-a0cfa1011b05:
    contentColumnType: string
    fieldGroup: null
    handle: background
    instructions: ''
    name: Background
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - light
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - secondary
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Dropdown
  83d4dc8a-1b63-4599-870b-4d1cc105caac:
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: ''
    name: Position
    searchable: false
    settings:
      default: center
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - '1'
          -
            - right
            - '1'
          -
            - full
            - '1'
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: site
    type: rias\positionfieldtype\fields\Position
  e6e287b3-e9ab-43a5-a89a-11cdc02cef8b:
    contentColumnType: string
    fieldGroup: null
    handle: page
    instructions: ''
    name: Page
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: copy
name: Copy
sortOrder: 1
