field: b20240ab-6495-4623-b16d-6ac8c2e80970 # Layout
fieldLayouts:
  b2800a3b-3f6e-4324-b465-38bcc15b4717:
    tabs:
      -
        elements:
          -
            fieldUid: 68e50d94-b4b1-4d05-9e0b-25a34a99f0c2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d4582d1-f3d3-4daf-b230-bfac4342a2ad
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cc68724b-9968-49b2-8670-e985542ac0fd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 42b8ae3a-c1e3-469c-8fd5-e7ef808705d1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6d4582d1-f3d3-4daf-b230-bfac4342a2ad:
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: ''
    name: Position
    searchable: false
    settings:
      default: full
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - '1'
          -
            - right
            - '1'
          -
            - full
            - '1'
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: site
    type: rias\positionfieldtype\fields\Position
  42b8ae3a-c1e3-469c-8fd5-e7ef808705d1:
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: ''
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  68e50d94-b4b1-4d05-9e0b-25a34a99f0c2:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:514e7215-b04f-4f9b-a70b-d98aad0cd088' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:514e7215-b04f-4f9b-a70b-d98aad0cd088' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  cc68724b-9968-49b2-8670-e985542ac0fd:
    contentColumnType: string
    fieldGroup: null
    handle: aspectRatio
    instructions: ''
    name: 'Aspect Ratio'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Panorama
            -
              - value
              - panorama
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Hero
            -
              - value
              - hero
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Dropdown
handle: image
name: Image
sortOrder: 2
