field: b20240ab-6495-4623-b16d-6ac8c2e80970 # Layout
fieldLayouts:
  5b117df4-cd21-41c6-af17-6427be704968:
    tabs:
      -
        elements:
          -
            fieldUid: fbffcd07-17a8-4624-8840-cf2dcc176576
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a752353-0cc8-4cc6-b718-a983bea38b9d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0a752353-0cc8-4cc6-b718-a983bea38b9d:
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: ''
    name: Position
    searchable: false
    settings:
      default: center
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - '1'
          -
            - right
            - '1'
          -
            - full
            - ''
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
  fbffcd07-17a8-4624-8840-cf2dcc176576:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:514e7215-b04f-4f9b-a70b-d98aad0cd088' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '2'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:514e7215-b04f-4f9b-a70b-d98aad0cd088' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: images
name: Images
sortOrder: 3
