field: b20240ab-6495-4623-b16d-6ac8c2e80970 # Layout
fieldLayouts:
  10b3c60a-5e82-4944-b752-dbb2c6402769:
    tabs:
      -
        elements:
          -
            fieldUid: d7f7c9e5-f694-40d3-b0d9-59ea882c043c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b5468e5-20ca-4d79-8f3e-ec8a6b321788
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1b5468e5-20ca-4d79-8f3e-ec8a6b321788:
    contentColumnType: text
    fieldGroup: null
    handle: cite
    instructions: ''
    name: Cite
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  d7f7c9e5-f694-40d3-b0d9-59ea882c043c:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 4
