field: b20240ab-6495-4623-b16d-6ac8c2e80970
fieldLayouts:
  dfc12b9d-0635-4339-9a92-292d5378cbed:
    tabs:
      -
        elements:
          -
            fieldUid: cd439129-b1d1-4ca0-87bc-7563f1e003f6
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: afe28c73-81ca-4837-9d03-6385f114c155
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  afe28c73-81ca-4837-9d03-6385f114c155:
    contentColumnType: text
    fieldGroup: null
    handle: cite
    instructions: ''
    name: Cite
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cd439129-b1d1-4ca0-87bc-7563f1e003f6:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 2
