fieldLayouts:
  0cb1eba5-ca1d-44f5-8a36-2e1087c68b36:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Page
        sortOrder: 1
handle: cookiePolicy
hasTitleField: false
name: 'Cookie Policy'
section: 6f92b28c-ef6c-44eb-9780-53d52b1745b2
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
