fieldLayouts:
  0a92e416-af30-4b64-98be-eb8d05f2b5e7:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: f2e7b889-f463-4dfa-9f10-8da7f7616b47
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 44f8bb4e-fd2e-4680-997b-a3b80266a3e3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e61b08dc-3ef1-4300-952e-8472bb10a02e
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Location
        sortOrder: 1
handle: location
hasTitleField: false
name: Location
section: e9df79f9-d58f-4b00-8a78-29f6e4c25b90
sortOrder: 1
titleFormat: '{section.name|raw}'
