fieldLayouts:
  3445d436-b4d5-419f-a486-5073091856d9:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: f2e7b889-f463-4dfa-9f10-8da7f7616b47
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 44f8bb4e-fd2e-4680-997b-a3b80266a3e3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: dbb9d3a4-36d1-4a8d-bc0b-2727aba8216d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Tab 1'
        sortOrder: 1
handle: foodAndDrink
hasTitleField: false
name: 'Food and Drink'
section: 09dfbb9e-dd73-439d-8854-798312bf7b34
sortOrder: 1
titleFormat: '{section.name|raw}'
