fieldLayouts:
  6678d84d-4646-4934-bcc2-94287fbcf2a9:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: b466e6e9-4c8b-426a-91fe-f464370bb90f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Tab 1'
        sortOrder: 1
handle: info
hasTitleField: false
name: Info
section: 0b1c8c0c-3520-4470-bcdb-1b8b477bb9ed
sortOrder: 1
titleFormat: '{section.name|raw}'
