fieldLayouts:
  d5d275f7-ec4b-48fc-88c2-77fc8ddc002f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: f528f828-ed26-4491-9e93-8795fa0c2de4 # Date
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 700e15d2-74b7-4a87-91fd-6a59571d15db # Festival Start
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 08bfc530-eca6-43f9-ab46-42036ceda84d # Show Start
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 254fe20a-80be-4df7-8576-4c5133b1a3c3 # Show Finish
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 379ef124-adcb-4f40-a627-a988a9cb97b1 # Acts
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b20240ab-6495-4623-b16d-6ac8c2e80970 # Layout
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 520b1a0f-524b-4fae-8323-c5b3a9c28e9b # Ticket Link
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6a728bad-ec01-4758-9fe5-e86072724c73 # Ticket Price
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 451a15b7-3f3a-4083-9372-7a44670edd9b # Sold Out
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Shows
        sortOrder: 1
handle: shows
hasTitleField: true
name: Shows
section: 3b5101c5-1de7-47b8-9ccc-3cb7ad88156f
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
