app: 813-studio
ssh_url: 813-studio@deploy.eu2.frbit.com
ssh_path: null
git_remote: 813-studio/master
before:
    code/up:
        - 'echo  "Script example: " $(git rev-parse HEAD)'
after:
    code/down:
        - 'php craft migrate/all'
