baseUrl: 'https://greenwichcomedyfestival.test'
enabled: true
handle: greenwich
hasUrls: true
language: en-GB
name: 'Greenwich Comedy Festival'
primary: false
siteGroup: 775858db-8a1e-4b3c-b3dd-0b0018aa9cd8
sortOrder: 2
