contentColumnType: datetime
fieldGroup: c0d2f2a9-d0ea-493b-b929-9e75435e77c1
handle: showFinish
instructions: ''
name: 'Show Finish'
searchable: true
settings:
  minuteIncrement: '15'
  showDate: false
  showTime: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
