contentColumnType: text
fieldGroup: 40ab6dfa-cf95-4cd7-8011-6b5415306b5c
handle: foodCopy
instructions: ''
name: 'Food Copy'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Custom.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
