contentColumnType: string
fieldGroup: c0d2f2a9-d0ea-493b-b929-9e75435e77c1 # Shows
handle: acts
instructions: ''
name: Acts
searchable: true
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Add an act'
  showSiteMenu: true
  source: null
  sources:
    - 'section:26101bcb-f76c-45f2-89e2-3a7abda62d69'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
