contentColumnType: string
fieldGroup: 40ab6dfa-cf95-4cd7-8011-6b5415306b5c # Home
handle: featuredActs
instructions: ''
name: 'Featured Acts'
searchable: true
settings:
  contentTable: '{{%matrixcontent_featuredacts}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
