contentColumnType: string
fieldGroup: 3a0a7e49-63bf-423e-953e-a601e8639af6 # About
handle: highlights
instructions: ''
name: Highlights
searchable: false
settings:
  contentTable: '{{%matrixcontent_highlights}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
