contentColumnType: text
fieldGroup: f8d4448a-1e97-4a1d-9e28-b16c546a43d4
handle: logo
instructions: ''
name: Logo
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
