contentColumnType: string(255)
fieldGroup: f8d4448a-1e97-4a1d-9e28-b16c546a43d4 # Globals
handle: previousSite
instructions: ''
name: 'Previous Site'
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Url
