contentColumnType: boolean
fieldGroup: f8d4448a-1e97-4a1d-9e28-b16c546a43d4 # Globals
handle: showAddress
instructions: ''
name: 'Show Address'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
