contentColumnType: text
fieldGroup: c0d2f2a9-d0ea-493b-b929-9e75435e77c1 # Shows
handle: ticketPrice
instructions: ''
name: 'Ticket Price'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
