contentColumnType: string
fieldGroup: 698fb214-9c3e-4792-8ddc-37ba1d9cdb8d # Food + Drink
handle: traders
instructions: ''
name: Traders
searchable: true
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Add a trader'
  showSiteMenu: true
  source: null
  sources:
    - 'section:11c123fc-7137-41fd-8d64-57a99e3852d7' # Traders
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
