fieldLayouts:
  78b4a8c8-e61c-4575-a46e-e9955ce064fa:
    tabs:
      -
        fields:
          1e915834-a9e5-4736-aa84-209add6fb4e3:
            required: false
            sortOrder: 7
          37935d71-f171-4ecf-96a8-d5a1092a6b9c:
            required: false
            sortOrder: 4
          3bad206c-e807-43db-931f-74b0bcd415dc:
            required: false
            sortOrder: 9
          5f69b46d-451c-44ae-939a-dfdcb992fe17:
            required: false
            sortOrder: 6
          7296570e-e89d-48bf-8e3d-55553f2238fb:
            required: false
            sortOrder: 3
          8d631758-1c23-4e9e-9107-15e523e319a3:
            required: false
            sortOrder: 1
          b49d5c36-50aa-4f0c-bdf2-3761dc15876d:
            required: false
            sortOrder: 8
          b98e4070-1198-44ee-a715-f62bffc2accd:
            required: false
            sortOrder: 5
          fbc5a213-4224-418d-9e40-f2b25d93211d:
            required: false
            sortOrder: 2
        name: 'Tab 1'
        sortOrder: 1
handle: event
name: Event
