fieldLayouts:
  7f46c47f-e2fb-405d-8574-84c8c077f041:
    tabs:
      -
        elements:
          -
            fieldUid: 44f8bb4e-fd2e-4680-997b-a3b80266a3e3 # Copy
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f2e7b889-f463-4dfa-9f10-8da7f7616b47 # Image
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0cf23571-d9b1-4717-b559-8b5e8d622963 # Tickets on Sale
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8d78b256-eda6-41e1-b2e2-8ffbb8af6db6 # Show Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: holding
name: Holding
