enableVersioning: true
handle: bundles
name: Bundles
propagationMethod: all
siteSettings:
  0c3138de-61c9-4e2d-8982-aa68a6127f5f:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'bundles/{slug}'
  5ea3bf2d-32a9-4d43-87c4-90b7c5344e02:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'bundles/{slug}'
  686641b5-66fd-466f-869e-d61dcf15e5ef: # Greenwich Comedy Festival
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'bundles/{slug}'
  da261e74-add5-49fb-88aa-0bf4cd89b508: # Bristol Comedy Garden
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'bundles/{slug}'
structure:
  maxLevels: 1
  uid: 34580a1b-db4f-4226-89a6-e31076996db1
type: structure
