enableVersioning: true
handle: foodAndDrink
name: 'Food and Drink'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  0c3138de-61c9-4e2d-8982-aa68a6127f5f: # Default
    enabledByDefault: true
    hasUrls: true
    template: default/food-and-drink/index
    uriFormat: food-and-drink
  5ea3bf2d-32a9-4d43-87c4-90b7c5344e02: # Brighton Comedy Garden
    enabledByDefault: true
    hasUrls: true
    template: default/food-and-drink/index
    uriFormat: food-and-drink
  686641b5-66fd-466f-869e-d61dcf15e5ef: # Greenwich Comedy Festival
    enabledByDefault: true
    hasUrls: true
    template: default/food-and-drink/index
    uriFormat: food-and-drink
  da261e74-add5-49fb-88aa-0bf4cd89b508: # Bristol Comedy Garden
    enabledByDefault: true
    hasUrls: true
    template: default/food-and-drink/index
    uriFormat: food-and-drink
type: single
