enableVersioning: true
handle: showsPage
name: 'Shows Page'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  0c3138de-61c9-4e2d-8982-aa68a6127f5f:
    enabledByDefault: true
    hasUrls: true
    template: default/shows/index
    uriFormat: shows
  5ea3bf2d-32a9-4d43-87c4-90b7c5344e02:
    enabledByDefault: true
    hasUrls: true
    template: default/shows/index
    uriFormat: shows
  686641b5-66fd-466f-869e-d61dcf15e5ef:
    enabledByDefault: true
    hasUrls: true
    template: default/shows/index
    uriFormat: shows
  da261e74-add5-49fb-88aa-0bf4cd89b508:
    enabledByDefault: true
    hasUrls: true
    template: default/shows/index
    uriFormat: shows
type: single
