enableVersioning: true
handle: shows
name: Shows
propagationMethod: none
siteSettings:
  7cd65d79-ef2b-43ed-9b9a-8cd57ed3c87e: # Brighton Comedy Garden
    enabledByDefault: true
    hasUrls: true
    template: default/shows/entry
    uriFormat: 'shows/{slug}'
  686641b5-66fd-466f-869e-d61dcf15e5ef: # Greenwich Comedy Festival
    enabledByDefault: true
    hasUrls: true
    template: default/shows/entry
    uriFormat: 'shows/{slug}'
  af369054-89d8-40f7-a369-99437baee95d: # St Albans Comedy Garden
    enabledByDefault: true
    hasUrls: true
    template: default/shows/entry
    uriFormat: 'shows/{slug}'
  da261e74-add5-49fb-88aa-0bf4cd89b508: # Bristol Comedy Garden
    enabledByDefault: true
    hasUrls: true
    template: default/shows/entry
    uriFormat: 'shows/{slug}'
structure:
  maxLevels: null
  uid: 2b767bf6-52ff-4623-953f-5c3aab4949a9
type: structure
