enableVersioning: false
handle: tickets
name: Tickets
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  0c3138de-61c9-4e2d-8982-aa68a6127f5f:
    enabledByDefault: true
    hasUrls: true
    template: default/tickets/tickets
    uriFormat: tickets
  5ea3bf2d-32a9-4d43-87c4-90b7c5344e02:
    enabledByDefault: true
    hasUrls: true
    template: default/tickets/tickets
    uriFormat: tickets
  686641b5-66fd-466f-869e-d61dcf15e5ef:
    enabledByDefault: true
    hasUrls: true
    template: default/tickets/tickets
    uriFormat: tickets
  da261e74-add5-49fb-88aa-0bf4cd89b508:
    enabledByDefault: true
    hasUrls: true
    template: default/tickets/tickets
    uriFormat: tickets
type: single
